## Create persistent volume claim for minio to store data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-fs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
## Run minio fs deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-fs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-fs
  template:
    metadata:
      labels:
        app: minio-fs
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: minio-fs-pvc
      containers:
      - name: minio-fs
        volumeMounts:
        - name: data
          mountPath: "/data"
        image: minio/minio:latest
        args:
        - server
        - /data
        env:
        - name: MINIO_ROOT_USER
          value: "minio"
        - name: MINIO_ROOT_PASSWORD
          value: "minio123"
        ports:
        - containerPort: 9000
          hostPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-fs
spec:
  ports:
  - port: 9000
    name: http
  selector:
    app: minio-fs
