apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: items
  namespace: items
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: items
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 99
