apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: zerodowntime
spec:
  host: zerodowntime
  subsets:
  - name: primary
    labels:
      version: v3
  - name: canary
    labels:
      version: v4
