---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: items
  namespace: flux-system
spec:
  interval: 1m0s
  dependsOn:
    - name: istio-system
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: items
  targetNamespace: items

