apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zerodowntime
  namespace: zero
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
  - timeout: 50s
    route:
    - destination:
        host: zerodowntime.zero.svc.cluster.local
